# Download the Google AudioSet

In [1]:
import pandas as pd

In [2]:
unbalanced_df = pd.read_csv('../audioset-processing/data/unbalanced_train_segments.csv',header=[0,1])

In [3]:
unbalanced_df

,# num_ytids=2041789,num_segs=2041789,num_unique_labels=527,num_positive_labels=4020212
,# YTID,start_seconds,end_seconds,positive_labels
0,---1_cCGK4M,0.0,10.0,"/m/01g50p,/m/0284vy3,/m/06d_3,/m/07jdr,/m/07rwm0c"
1,---2_BBVHAA,30.0,40.0,/m/09x0r
2,---B_v8ZoBY,30.0,40.0,/m/04rlf
3,---EDNidJUA,30.0,40.0,"/m/02qldy,/m/02zsn,/m/05zppz,/m/09x0r"
4,---N4cFAE1A,21.0,31.0,"/m/04rlf,/m/09x0r"
...,...,...,...,...
1048568,PCMPQII_0kI,0.0,8.0,/m/0838f
1048569,PCMSpXTd92s,30.0,40.0,/m/09x0r
1048570,PCMh6401_3k,17.0,27.0,/m/09x0r
1048571,PCMnoJnDJ1I,30.0,40.0,"/m/02lkt,/m/03mb9,/m/04rlf,/m/07gxw"
1048572,PCMr_3tBMD8,450.0,460.0,/m/09x0r

In [4]:
# get the youtube videos labeled as city/urban or rural/nature
urban_ind = unbalanced_df[unbalanced_df.columns[3]].str.contains('/t/dd00128')
natural_ind = unbalanced_df[unbalanced_df.columns[3]].str.contains('/t/dd00129')

In [5]:
df_urban = unbalanced_df[urban_ind]
df_natural = unbalanced_df[natural_ind]

In [6]:
# randomly sampled 10,000 files from more than 20,000 files
df_urban_sampled = df_urban.sample(n=10000, random_state=23, axis=0)
df_urban_sampled

,# num_ytids=2041789,num_segs=2041789,num_unique_labels=527,num_positive_labels=4020212
,# YTID,start_seconds,end_seconds,positive_labels
1027208,OVAMx6s2YSU,30.0,40.0,"/m/04rlf,/m/05zppz,/m/09x0r,/t/dd00128"
761926,G22u2KOIhhU,30.0,40.0,"/m/04rlf,/m/09x0r,/t/dd00128"
993129,NOCmIXHhH4I,30.0,40.0,"/m/015p6,/m/09x0r,/t/dd00128"
1022603,OLQd2tOFkX4,240.0,250.0,"/m/012f08,/m/04rlf,/t/dd00128"
404503,6XQpgD1xHRo,30.0,40.0,"/m/03qtwd,/m/09x0r,/t/dd00128"
...,...,...,...,...
597476,BHAgYGoxk-Y,0.0,10.0,"/m/06_fw,/t/dd00128"
581649,AsVxggc-0nw,30.0,40.0,"/m/09x0r,/m/0jbk,/t/dd00128"
943486,LmR67xuY0EQ,10.0,20.0,/t/dd00128
1015936,O7QHEAo8SBA,20.0,30.0,"/m/02mk9,/m/07yv9,/m/0k4j,/t/dd00128"
516399,9HI1cOAY7Sg,30.0,40.0,"/m/01g50p,/m/07jdr,/m/07yv9,/t/dd00128"

In [7]:
df_natural_sampled = df_natural.sample(n=10000, random_state=23, axis=0)
df_natural_sampled

,# num_ytids=2041789,num_segs=2041789,num_unique_labels=527,num_positive_labels=4020212
,# YTID,start_seconds,end_seconds,positive_labels
411183,6gc7A6nfJn4,290.0,300.0,"/m/09x0r,/t/dd00129"
932142,LPpyqHWGszk,0.0,10.0,"/m/07yv9,/t/dd00129"
375508,5rvuGtwUt2o,360.0,370.0,"/m/01rd7k,/m/028v0c,/t/dd00129"
882125,JmuBJVcNzzs,8.0,18.0,/t/dd00129
422014,6wobYMiuWPE,470.0,480.0,"/m/07yv9,/m/09x0r,/t/dd00129"
...,...,...,...,...
641486,CT5GSfZBl0s,5.0,15.0,"/m/09x0r,/t/dd00129"
335551,5-TQDc5lHYo,0.0,10.0,"/m/09x0r,/t/dd00125,/t/dd00129"
416978,6pCRDkR_07I,10.0,20.0,"/m/06d_3,/m/07jdr,/m/07yv9,/t/dd00129"
719887,El-8bArXiVM,30.0,40.0,"/m/09x0r,/m/0h0rv,/m/0jbk,/t/dd00129"
199070,2MbFVsGlX7E,30.0,40.0,"/m/07yv9,/t/dd00129"

In [8]:
df = pd.concat([df_urban_sampled, df_natural_sampled])
df

,# num_ytids=2041789,num_segs=2041789,num_unique_labels=527,num_positive_labels=4020212
,# YTID,start_seconds,end_seconds,positive_labels
1027208,OVAMx6s2YSU,30.0,40.0,"/m/04rlf,/m/05zppz,/m/09x0r,/t/dd00128"
761926,G22u2KOIhhU,30.0,40.0,"/m/04rlf,/m/09x0r,/t/dd00128"
993129,NOCmIXHhH4I,30.0,40.0,"/m/015p6,/m/09x0r,/t/dd00128"
1022603,OLQd2tOFkX4,240.0,250.0,"/m/012f08,/m/04rlf,/t/dd00128"
404503,6XQpgD1xHRo,30.0,40.0,"/m/03qtwd,/m/09x0r,/t/dd00128"
...,...,...,...,...
641486,CT5GSfZBl0s,5.0,15.0,"/m/09x0r,/t/dd00129"
335551,5-TQDc5lHYo,0.0,10.0,"/m/09x0r,/t/dd00125,/t/dd00129"
416978,6pCRDkR_07I,10.0,20.0,"/m/06d_3,/m/07jdr,/m/07yv9,/t/dd00129"
719887,El-8bArXiVM,30.0,40.0,"/m/09x0r,/m/0h0rv,/m/0jbk,/t/dd00129"
199070,2MbFVsGlX7E,30.0,40.0,"/m/07yv9,/t/dd00129"

In [9]:
df.to_csv('../audioset-processing/data/unbalanced_train_segments_sampled10000_UrbanNatural.csv', index=False)

# Download files

In [7]:
from distutils.sysconfig import get_python_lib
print(get_python_lib())

/Users/andrewchang/opt/anaconda3/envs/AcousticEnv/lib/python3.8/site-packages

In [1]:
import os
os.getcwd()

'/Users/andrewchang/Springboard_GitHub/Capstone_AcousticEnv/notebooks'

In [2]:
os.chdir('/Users/andrewchang/Springboard_GitHub/Capstone_AcousticEnv/audioset-processing')
os.getcwd()

'/Users/andrewchang/Springboard_GitHub/Capstone_AcousticEnv/audioset-processing'

Note (Feb 26): 
make this change to the file /Users/andrewchang/opt/anaconda3/envs/AcousticEnv/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py
https://github.com/ytdl-org/youtube-dl/issues/31530
original line: 'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,

In [ ]:
# nature unbalanced set
! python3 process.py download -c "Outside, rural or natural" -d ../data/raw/GoogleAudioSet_unbalanced_list --label_file data/class_labels_indices.csv --csv_dataset data/unbalanced_train_segments_sampled10000_UrbanNatural.csv

In [ ]:
# city unbalanced set
! python3 process.py download -c "Outside, urban or manmade" -d ../data/raw/GoogleAudioSet_unbalanced_list --label_file data/class_labels_indices.csv --csv_dataset data/unbalanced_train_segments_sampled10000_UrbanNatural.csv

In [ ]:
# nature evaluation set
! python3 process.py download -c "Outside, rural or natural" -d ../data/raw/GoogleAudioSet_eval_list --label_file data/class_labels_indices.csv --csv_dataset data/eval_segments.csv

In [ ]:
# city evaluation set
! python3 process.py download -c "Outside, urban or manmade" -d ../data/raw/GoogleAudioSet_eval_list --label_file data/class_labels_indices.csv --csv_dataset data/eval_segments.csv